# Generated by Django 2.1 on 2019-01-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20181220_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
