# Generated by Django 2.1.1 on 2019-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(on_delete=True, to='comment.Comment'),
        ),
    ]
