# Generated by Django 2.1 on 2019-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190105_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_email',
            field=models.EmailField(default='chuxiaoyi@chuxiaoyi@cn', max_length=50, verbose_name='被回复的邮箱'),
        ),
    ]
